### ISSUE TITLE
more FA:S guns

### ISSUE THREAD

**Issue by CounterCraftz** [GMDevinity/BattleRoyaleIssues#179] opened 2019-10-03 22:33 UTC
It might be worth looking into, alongside the author's future releases
https://steamcommunity.com/sharedfiles/filedetails/?id=1876337153

**Comment by Donkie** [comment] 2019-11-18 21:08
https://steamcommunity.com/sharedfiles/filedetails/?id=462119296

**Comment by Donkie** [comment] 2020-08-13 14:41
Duplicate of #173

**Closed as completed by Donkie** 2020-08-13 14:41 UTC
Labels: Idea
