### ISSUE TITLE
End card at the end of the round

### ISSUE THREAD

**Issue by bjincy** [GMDevinity/BattleRoyaleIssues#157] opened 2018-07-18 18:17 UTC
The idea is to have an end card like in flood for 5-10 seconds before the pregame.  it would show the winner and maybe their round stats, and then smaller categories like most kills, furthest kill, first blood, furthest distance ran, and most time spent in the air.  we can give these things better names like "Marathon" and "I feel like a bird"

**Comment by Donkie** [comment] 2018-07-19 13:00
Duplicate of #17

**Closed as completed by Donkie** 2018-07-19 13:00 UTC
