### ISSUE TITLE
Deathmatch

### ISSUE THREAD

**Issue by SirJuanCarlos** [GMDevinity/BattleRoyaleIssues#170] opened 2018-09-22 21:03 UTC
Spectating is a bit boring and the pre game could be spiced up a bit. Id do that by adding a deatchmatch. Itd be an optional thing for spectators and a replacement for the knife battle in the pregame.

Deathmatch:

After dying you join a spectator deathmatch (like in ttt servers) , You cant be seen by alive players, cant destroy anything, have no corpse and cant open doors (you can just walk through them like a ghost) .

Weapons:
Id would work like weapons in flood. You have standard weapons, which are weaker than bought weapons. You use your ingame coins to buy weapons. For example the standard loadout is an SG 552 and a M1911, And you could buy a Raging bull for 100 coins which would replace the 1911 and a galil for 230 coins which would replace the SG 552.
You would also be able to obtain the weapons from the roulette.

**Comment by Donkie** [comment] 2020-08-13 12:46
Duplicate of #36

**Closed as completed by Donkie** 2020-08-13 12:46 UTC
